apps/staff/urls.py
from django.urls import path, include
from apps.staff.viewsets import StaffViewSet, RoleViewSet

from rest_framework.routers import DefaultRouter
from rest_framework_jwt.views import obtain_jwt_token

from apps.staff.views import StaffList, StaffNew


from apps.staff.views import UserList, UserCreate, UserUpdate, UserDelete
# -------------------------------------------------------->
# Routers ApI
routers = DefaultRouter()
routers.register(r'', StaffViewSet)
routers.register(r'role', RoleViewSet)

app_name = 'staff'

urlpatterns = [

    # -------------------------------------------------------->
    # Path Routers API
    path('api/', include(routers.urls)),

    # -------------------------------------------------------->
    # Path Token

    path('login/', obtain_jwt_token),

    # -------------------------------------------------------->
    # Path Staff

    path('', StaffList.as_view(), name='staff_list'),
    path('new', StaffNew.as_view(), name='staff_new'),

    # -------------------------------------------------------->
    # Path User

    path('user', UserList.as_view(), name='user_list'),
    path('New', UserCreate.as_view(), name='user_new'),
    path('Edit/<int:pk>', UserUpdate.as_view(), name='user_update'),
    path('delete/<int:pk>', UserDelete.as_view(), name='user_delete'),

]

me_rest/urls.py
from django.contrib import admin
from django.urls import path, include
from me_rest.views import HomeView
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('/home', HomeView.as_view(), name='home'),
    path('staff/', include('apps.staff.urls')),
    path('store/', include('apps.store.urls')),
    path('arrangement/', include('apps.arrangement.urls')),
    path('product/', include('apps.product.urls')),
    path('cellar/', include('apps.cellar.urls')),
    path('buy/', include('apps.buy.urls')),
    path('sale/', include('apps.sale.urls')),

]

apps/staff/models.py
from django.db import models
from apps.store.models import Store
from django.contrib.auth.models import User


# ------------------------------------------------------------------------------------>
# Model Role


class Role(models.Model):
    name = models.CharField(max_length=100, null=True)
    description = models.CharField(max_length=100, null=True)

    class Meta:
        verbose_name = 'Role'
        verbose_name_plural = 'Role'

    def __str__(self):
        return self .name


# ------------------------------------------------------------------------------------->
# Model Staff


class Staff(models.Model):
    idStaff = models.CharField(max_length=30, primary_key=True)
    name = models.CharField(max_length=100, null=True)
    birthday = models.DateField(null=True)
    direction = models.CharField(max_length=100, null=True)
    phone = models.CharField(max_length=100, null=True)
    phone2 = models.CharField(max_length=100, null=True)
    email = models.EmailField(max_length=100, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    role = models.ForeignKey(Role, on_delete=models.CASCADE, null=True)
    photo = models.ImageField(max_length=100, null=True)
    store = models.ForeignKey(Store, on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name = 'Staff'
        verbose_name_plural = 'Staff'

    def __str__(self):
        return self.idStaff


# ------------------------------------------------------------------------------------->

apps/staff/forms.py
from django import forms
from apps.staff.models import Staff, Role
from django.contrib.auth.models import User


# -------------------------------------------------------->
# Forms User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__'
        labels = {
            'username': 'Nombre de usuario',
            'last_name': 'Nombre',
            'first_name': 'Apellido',
            'password': 'Password',
            'email': 'Correo electronico'
        }
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }


# -------------------------------------------------------->
# Forms role

class RoleForm(forms.ModelForm):
    class Meta:
        model = Role
        fields = (
            'name',
            'description',
        )
        labels = {
            'name': 'Nombre Del Rol',
            'description': 'Descripcion del rol',
        }


# -------------------------------------------------------->
# Form staff

class StaffForm(forms.ModelForm):
    class Meta:
        model = Staff
        fields = [
            'idStaff',
            'name',
            'direction',
            'birthday',
            'phone',
            'phone2',
            'email',
            'user',
            'role',
            'photo',

        ]

        labels = {
            'idStaff': 'Id',
            'name': 'Name',
            'direction': 'Dirreccion',
            'birthday': 'Nacimiento',
            'phone': 'Telefono',
            'phone2': 'Celular',
            'email': 'Correo Electronico',
            'user': 'Usuario',
            'role': 'Rol',
            'photo': 'Foto',

        }

        widgets = {
            'idStaff': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Id personal',

                }
            ),
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Nombre Completo',
                }
            ),
            'direction': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Dirreccion',
                }
            ),
            'birthday': forms.DateInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Fecha de nacimiento',
                }
            ),
            'phone': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Telefono',
                }
            ),
            'phone2': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Celular',
                }
            ),
            'email': forms.EmailInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Celular',
                }
            ),
            'user': forms.Select(
                attrs={
                    'class': 'form-control',
                }
            ),
            'role': forms.Select(
                attrs={
                    'class': 'form-control',
                }
            ),

        }

apps/staff/views.py
from rest_framework.exceptions import PermissionDenied
from rest_framework.generics import get_object_or_404

from apps.staff.models import Staff, User
from apps.staff.forms import StaffForm, UserForm
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy


# ------------------------------------------------------------------------------------>
# view Staff

class StaffList(ListView):
    model = Staff
    template_name = 'staff/staff_list.html'
    context_object_name = 'staff_list'
    queryset = Staff.objects.all()


class StaffNew(CreateView):
    model = Staff
    form_class = StaffForm
    template_name = 'staff/staff_form.html'
    success_url = reverse_lazy('#')


# ------------------------------------------------------------------------------------>
# view User

class UserList(ListView):
    Model = User
    template_name = 'staff/user/user_list.html'
    context_object_name = 'user_list'
    queryset = User.objects.all()


class UserCreate(CreateView):
    model = User
    form_class = UserForm
    template_name = 'staff/user/user_form.html'
    success_url = reverse_lazy('staff:user_list')


class UserUpdate(UpdateView):
    model = User
    form_class = UserForm
    template_name = 'staff/user/user_form.html'
    success_url = reverse_lazy('staff:user_list')


class UserDelete(DeleteView):
    model = User
    form_class = UserForm
    template_name = 'staff/user/user_confirm_delete.html'
    success_url = reverse_lazy('staff:user_list')

templates/staff/staff_form.html
{% extends 'home/home.html' %}
{% block pageContent %}
    <div class="card mx-3">
        <div class="card-header">
            <strong>Registro Personal</strong>
        </div>
        <div class="card-body">
            {% csrf_token %}
            <form>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="#">{{ form.idStaff.label }}</label>
                        {{ form.idStaff }}
                    </div>
                    <div class="form-group col-md-6">
                        <label for="#">{{ form.name.label }}</label>
                        {{ form.name }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="#">{{ form.direction.label }}</label>
                        {{ form.direction }}
                    </div>
                    <div class="form-group col-md-6">
                        <label for="#">{{ form.birthday.label }}</label>
                        {{ form.birthday }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="#">{{ form.phone.label }}</label>
                        {{ form.phone }}
                    </div>
                    <div class="form-group col-md-6">
                        <label for="#">{{ form.phone2.label }}</label>
                        {{ form.phone2 }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="#">{{ form.email.label }}</label>
                        {{ form.email }}
                    </div>
                    <div class="form-group col-md-6">
                        <label for="#">{{ form.user.label }}</label>
                        {{ form.user }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="form-group col-md-6">
                        <label for="#">{{ form.role.label }}</label>
                        {{ form.role }}
                    </div>
                <div class="form-group col-md-6 mt-4">
                    <label for="#">{{ form.photo.label }}</label>
                    {{ form.photo }}
                </div>
                <button type="submit">SUBMIT</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/staff/staff_list.html
{% extends 'home/home.html' %}
{% block pageContent %}
    {% if staff_list %}
        <div class="card mx-3">
            <div class="card-body">
                <a href="{% url 'staff:staff_new' %}" class="btn btn-primary btn-icon-split mb-3">
                    <span class="icon text-white-50">
                      <i class="fas fa-plus"></i>
                    </span>
                    <span class="text">Agregar</span>
                </a>
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Usuario</th>
                        <th scope="col">Tienda</th>
                        <th scope="col">Role</th>
                        <th scope="col">Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for staff in staff_list %}
                        <td>{{ staff.idStaff }}</td>
                        <td>{{ staff.name }}</td>
                        <td>{{ staff.user }}</td>
                        <td>{{ staff.store }}</td>
                        <td>{{ staff.role }}</td>
                        <td>
                            <a href="#" class="btn btn-success btn-circle btn-sm">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a href="#" class="btn btn-danger btn-circle btn-sm">
                                <i class="fas fa-trash"></i>
                            </a>
                            <a href="#" class="btn btn-info btn-circle btn-sm">
                                <i class="fas fa-info-circle"></i>
                            </a>
                        </td>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% else %}
        <h1>No hay registros</h1>
    {% endif %}
{% endblock %}